#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided."
    echo "Run with ytt --help to view all available options."
    exit 1
fi
if [ $1 == "v" ];then
yt-dlp -o "/sdcard/yt/video/%(title)s.%(ext)s" $2
elif [ $1 == "a" ];then
yt-dlp -o "/sdcard/yt/audio/%(title)s.%(ext)s" -x $2
elif [ $1 == "id" ];then
yt-dlp -o "/sdcard/yt/%(title)s.%(ext)s" https://youtu.be/$2
elif [ $1 == "up" ];then
msg updating
wget -q -O ytt https://gist.githubusercontent.com/rooted-cyber/f4b28dacde6bc3bac07f1f29a3c394a7/raw/ytt
msg update? now
elif [ $1 == "--help" ];then
printf "\n yt [commands] [anylink]
Usage : yt v [anylink]
commands :
v -- download video
a -- download audio
id -- video/audio of youtube id 
up -- update ytt
\n\n"
else
printf "\n\n\033[1;91m invalid selection\n\n"
fi
